name: Run Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    # Cypress Docker image with Chrome v107
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
